mcms:
  enabled: false
  image: 
    tag: dev-ada354f9
  ingress:
    enabled: true
  ingress:
    enabled: true
  envs:
    CLUSTER_KEYCLOAK_RUNNER_ENABLED: "true"
    CLUSTER_KEYCLOAK_REDIRECT_URI: https://frontend.aaamedia.aaamedia-cluster.aws.gok.exxeta.info
    APP_CORS_ALLOWED_ORIGINS: https://frontend.aaamedia.aaamedia-cluster.aws.gok.exxeta.info,http://localhost:3000
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.aaamedia.aaamedia-cluster.aws.gok.exxeta.info/realms/d2-24-mcms-services

frontend:
  enabled: false
  image: 
    tag: dev-479c7962
  ingress:
    enabled: true
  ingress:
    enabled: true

keycloak:
  enabled: true
  extraEnvVars:
    - name: KEYCLOAK_PRODUCTION
      value: "false"
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_PROXY_HEADERS
      value: xforwarded
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HEALTH_ENABLED
      value: "true"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: Prefix
    hostname: keycloak.aaamedia.aaamedia-cluster.aws.gok.exxeta.info
    annotations:
      cert-manager.io/cluster-issuer: dns01-issuer
      certmanager.k8s.io/acme-challenge-type: dns01
      certmanager.k8s.io/acme-dns01-provider: route53
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    extraTls:
      - hosts:
        - '*.aaamedia.aaamedia-cluster.aws.gok.exxeta.info'
        secretName: aaamedia

  postgresql:
    enabled: true
    auth:
      postgresPassword: "false"
      username: bn_keycloak
      password: ""
      database: bitnami_keycloak
      existingSecret: ""
      secretKeys:
        userPasswordKey: password
    architecture: standalone
