global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom django.fullname in template.
  projectName: ""
  # image sets the repo,tag and pullPolicy of the project
  image:
    registry: ""
    tag: latest
    pullPolicy: Always

mcms:
  enabled: true

frontend:
  enabled: false

keycloak:
  enabled: false
  ## Bitnami/Keycloak Charts comes with PSQL Database, default enabled.
  ## We want to use the PSQL Database also for mcms backend, so we create our own.
  postgresql: 
    enabled: false

psql:
  enabled: false